spring:
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/eru-service-dev
    username: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true

server:
  port: 8069
  tomcat:
    max-swallow-size: -1

info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'

admin:
  crypto:
    algorithm: AES
    key1: '%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPe'
    key2: G+KaPdSgVkYp3s6v
    transformation: AES/CBC/PKCS5PADDING
  minYear: 2013
  storagePath: /media/bruno/UUI/storage
  web:
    allowed-origins: http://localhost:4200
    cross-origin-path-pattern: /**

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
