spring:
  main:
    banner-mode: OFF
    web-application-type: NONE
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/eru-service-dev
    username: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
    show-sql: true
  shell:
    interactive:
      enabled: true

#logging:
#  level:
#    root: off

admin:
  crypto:
    algorithm: AES
    key1: '%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPe'
    key2: G+KaPdSgVkYp3s6v
    transformation: AES/CBC/PKCS5PADDING
  minYear: 2013
  storagePath: /media/bruno/UUI/storage
